stages:
  - code
  - docs
  - test

.only-default:
  only:
    - master
    - merge_requests
    - tags
    - web

image: ghcr.io/maxking/mailman-ci-runner:latest

variables:
  LC_ALL: "C.UTF-8"
  HOME: "/builds"
  GIT_CEILING_DIRECTORIES: "/builds"

code-qa:
  stage: code
  needs: []
  extends: .only-default
  script:
  - tox -e qa

code-diffcov:
  stage: code
  needs: []
  script:
  - git config --global --add safe.directory "/builds/${CI_PROJECT_NAMESPACE}/mailman"
  - git config safe.directory
  - tox -e py311-diffcov
  only:
  - merge_requests

docs:
  stage: docs
  needs: []
  extends: .only-default
  script:
  - tox -e docs

test-sqlite:
  stage: test
  needs: []
  extends: .only-default
  parallel:
    matrix:
      - PYTHON_VER: ["39", "310", "311", "312", "313"]
  script:
    - tox -e "py$PYTHON_VER-nocov"

test-postgres:
  stage: test
  needs: []
  extends: .only-default
  variables:
    MAILMAN_EXTRA_TESTING_CFG: "/home/runner/configs/postgres.cfg"
    POSTGRES_DB: "mailman_test"
    POSTGRES_USER: "runner"
    POSTGRES_PASSWORD: "runner"
  services:
    - postgres:latest
  parallel:
    matrix:
      - PYTHON_VER: ["39", "310", "311", "312", "313"]
  script:
    - tox -e "py$PYTHON_VER-nocov-pg"

test-mysql:
  stage: test
  needs: []
  extends: .only-default
  variables:
    MAILMAN_EXTRA_TESTING_CFG: "/home/runner/configs/mysql.cfg"
    MYSQL_DATABASE: "test_mailman"
    MYSQL_ROOT_PASSWORD: "runner"
    MYSQL_USER: "runner"
    MYSQL_USER_PASSWORD: "runner"
  services:
    - mysql:5.6
  parallel:
    matrix:
      - PYTHON_VER: ["39", "310", "311", "312", "313"]
  script:
    - tox -e "py$PYTHON_VER-nocov-mysql"
