stages:
  - code
  - docs
  - test

.only-default:
  only:
    - master
    - merge_requests
    - tags
    - web

image: ghcr.io/maxking/mailman-ci-runner:latest

variables:
  POSTGRES_DB: "mailman_test"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: "runner"
  MYSQL_ROOT_PASSWORD: "runner"
  MYSQL_USER: "runner"
  MYSQL_USER_PASSWORD: "runner"
  MYSQL_DATABASE: "test_mailman"
  LC_ALL: "C.UTF-8"
  GIT_CEILING_DIRECTORIES: "/builds"
  HOME: "/builds"

code-qa:
  stage: code
  needs: []
  extends: .only-default
  script:
  - tox -e qa

code-diffcov:
  stage: code
  needs: []
  script:
  - git config --global --add safe.directory "/builds/${CI_PROJECT_NAMESPACE}/mailman"
  - git config safe.directory
  - tox -e py311-diffcov
  only:
  - merge_requests

docs:
  stage: docs
  needs: []
  extends: .only-default
  script:
  - tox -e docs

test-sqlite-39:
  stage: test
  needs: []
  extends: .only-default
  script:
    - tox -e py39-nocov

test-sqlite-310:
  stage: test
  needs: []
  extends: .only-default
  script:
    - tox -e py310-nocov

test-sqlite-311:
  stage: test
  needs: []
  extends: .only-default
  script:
    - tox -e py311-nocov

test-sqlite-312:
  stage: test
  needs: []
  extends: .only-default
  script:
    - tox -e py312-nocov

test-pgsql-39:
  stage: test
  needs: []
  extends: .only-default
  services:
  - postgres:latest
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/postgres.cfg tox -e py39-nocov-pg

test-pgsql-310:
  stage: test
  needs: []
  extends: .only-default
  services:
  - postgres:latest
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/postgres.cfg tox -e py310-nocov-pg

test-pgsql-311:
  stage: test
  needs: []
  extends: .only-default
  services:
  - postgres:latest
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/postgres.cfg tox -e py311-nocov-pg

test-mysql-39:
  stage: test
  needs: []
  extends: .only-default
  services:
  - mysql:5.6
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/mysql.cfg tox -e py39-nocov-mysql

test-mysql-310:
  stage: test
  needs: []
  extends: .only-default
  services:
  - mysql:5.6
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/mysql.cfg tox -e py310-nocov-mysql

test-mysql-311:
  stage: test
  needs: []
  extends: .only-default
  services:
  - mysql:5.6
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/mysql.cfg tox -e py311-nocov-mysql
